language: bash
services: docker

env:
  - VERSION=4.0-rc
  - VERSION=3.7
  - VERSION=3.6
  - VERSION=3.4
  - VERSION=3.2

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="mongo:$VERSION"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
