language: bash
services: docker

matrix:
  include:
    - os: linux
      env: VERSION=4.1
    - os: windows
      dist: 1803-containers
      env: VERSION=4.1 VARIANT=windows/windowsservercore-1803
    - os: linux
      env: VERSION=4.0
    - os: windows
      dist: 1803-containers
      env: VERSION=4.0 VARIANT=windows/windowsservercore-1803
    - os: linux
      env: VERSION=3.6
    - os: linux
      env: VERSION=3.4

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images
  - if [ "$TRAVIS_OS_NAME" = 'linux' ]; then wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash; fi

before_script:
  - env | sort
  - cd "$VERSION${VARIANT:+/$VARIANT}"
  - image="mongo:$VERSION${VARIANT:+$(basename "$VARIANT")}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
      if [ "$TRAVIS_OS_NAME" = 'windows' ]; then
        # TODO make the tests run successfully on Windows too!
        docker run --rm "$image" mongod --version
        docker run --rm "$image" mongo --version
      else
        ~/official-images/test/run.sh "$image"
      fi
    )

after_script:
  - docker images

# vim:set et ts=2 sw=2:
